// Mocks generated by Mockito from annotations
// in syncable/test/utils/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i12;
import 'dart:typed_data' as _i13;

import 'package:gotrue/gotrue.dart' as _i5;
import 'package:http/http.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:postgrest/postgrest.dart' as _i4;
import 'package:realtime_client/realtime_client.dart' as _i3;
import 'package:realtime_client/src/constants.dart' as _i11;
import 'package:realtime_client/src/push.dart' as _i7;
import 'package:realtime_client/src/types.dart' as _i10;
import 'package:supabase/supabase.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i4.PostgrestClient {
  _FakePostgrestClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i5.GoTrueClient {
  _FakeGoTrueClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i4.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStreamFilterBuilder_9 extends _i1.SmartFake
    implements _i2.SupabaseStreamFilterBuilder {
  _FakeSupabaseStreamFilterBuilder_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestQueryBuilder_10<T> extends _i1.SmartFake
    implements _i4.PostgrestQueryBuilder<T> {
  _FakePostgrestQueryBuilder_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestBuilder_11<T, S, R> extends _i1.SmartFake
    implements _i4.PostgrestBuilder<T, S, R> {
  _FakePostgrestBuilder_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_12 extends _i1.SmartFake implements Uri {
  _FakeUri_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_13<T> extends _i1.SmartFake implements _i6.Future<T> {
  _FakeFuture_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePush_14 extends _i1.SmartFake implements _i7.Push {
  _FakePush_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimePresence_15 extends _i1.SmartFake
    implements _i3.RealtimePresence {
  _FakeRealtimePresence_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_16 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_17 extends _i1.SmartFake
    implements _i8.StreamedResponse {
  _FakeStreamedResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_18 extends _i1.SmartFake
    implements _i5.GoTrueAdminApi {
  _FakeGoTrueAdminApi_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_19 extends _i1.SmartFake implements _i5.GoTrueMFAApi {
  _FakeGoTrueMFAApi_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueOAuthApi_20 extends _i1.SmartFake
    implements _i5.GoTrueOAuthApi {
  _FakeGoTrueOAuthApi_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTruePasskeyApi_21 extends _i1.SmartFake
    implements _i5.GoTruePasskeyApi {
  _FakeGoTruePasskeyApi_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_22 extends _i1.SmartFake implements _i5.AuthResponse {
  _FakeAuthResponse_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_23 extends _i1.SmartFake implements _i5.OAuthResponse {
  _FakeOAuthResponse_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_24 extends _i1.SmartFake
    implements _i5.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_25 extends _i1.SmartFake
    implements _i5.ResendResponse {
  _FakeResendResponse_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_26 extends _i1.SmartFake implements _i5.UserResponse {
  _FakeUserResponse_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_27 extends _i1.SmartFake implements Object {
  _FakeObject_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetClaimsResponse_28 extends _i1.SmartFake
    implements _i5.GetClaimsResponse {
  _FakeGetClaimsResponse_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_29 extends _i1.SmartFake implements _i5.User {
  _FakeUser_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_30 extends _i1.SmartFake implements _i5.Session {
  _FakeSession_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  @override
  _i2.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
            returnValueForMissingStub: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i3.RealtimeClient);

  @override
  _i4.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_3(this, Invocation.getter(#rest)),
            returnValueForMissingStub: _FakePostgrestClient_3(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i4.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i5.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_4(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeGoTrueClient_4(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i5.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i3.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i4.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? newHeaders) => super.noSuchMethod(
    Invocation.setter(#headers, newHeaders),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
            returnValueForMissingStub: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
            returnValueForMissingStub: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.SupabaseQuerySchema);

  @override
  _i4.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i4.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i3.RealtimeChannel>[],
            returnValueForMissingStub: <_i3.RealtimeChannel>[],
          )
          as List<_i3.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SupabaseQueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseQueryBuilder extends _i1.Mock
    implements _i2.SupabaseQueryBuilder {
  @override
  _i2.SupabaseStreamFilterBuilder stream({
    required List<String>? primaryKey,
    bool? private = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [], {
              #primaryKey: primaryKey,
              #private: private,
            }),
            returnValue: _FakeSupabaseStreamFilterBuilder_9(
              this,
              Invocation.method(#stream, [], {
                #primaryKey: primaryKey,
                #private: private,
              }),
            ),
            returnValueForMissingStub: _FakeSupabaseStreamFilterBuilder_9(
              this,
              Invocation.method(#stream, [], {
                #primaryKey: primaryKey,
                #private: private,
              }),
            ),
          )
          as _i2.SupabaseStreamFilterBuilder);

  @override
  _i4.PostgrestFilterBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestFilterBuilder_7<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_7<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i4.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i4.PostgrestFilterBuilder<dynamic> insert(
    Object? values, {
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [values],
              {#defaultToNull: defaultToNull},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
          )
          as _i4.PostgrestFilterBuilder<dynamic>);

  @override
  _i4.PostgrestFilterBuilder<dynamic> upsert(
    Object? values, {
    String? onConflict,
    bool? ignoreDuplicates = false,
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsert,
              [values],
              {
                #onConflict: onConflict,
                #ignoreDuplicates: ignoreDuplicates,
                #defaultToNull: defaultToNull,
              },
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
          )
          as _i4.PostgrestFilterBuilder<dynamic>);

  @override
  _i4.PostgrestFilterBuilder<dynamic> update(Map<dynamic, dynamic>? values) =>
      (super.noSuchMethod(
            Invocation.method(#update, [values]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
          )
          as _i4.PostgrestFilterBuilder<dynamic>);

  @override
  _i4.PostgrestFilterBuilder<dynamic> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
          )
          as _i4.PostgrestFilterBuilder<dynamic>);

  @override
  _i4.PostgrestFilterBuilder<int> count([
    _i4.CountOption? option = _i4.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [option]),
            returnValue: _FakePostgrestFilterBuilder_7<int>(
              this,
              Invocation.method(#count, [option]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_7<int>(
              this,
              Invocation.method(#count, [option]),
            ),
          )
          as _i4.PostgrestFilterBuilder<int>);

  @override
  _i4.PostgrestQueryBuilder<dynamic> retry({
    bool? enabled = true,
    int? count,
    Duration? requestTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#retry, [], {
              #enabled: enabled,
              #count: count,
              #requestTimeout: requestTimeout,
            }),
            returnValue: _FakePostgrestQueryBuilder_10<dynamic>(
              this,
              Invocation.method(#retry, [], {
                #enabled: enabled,
                #count: count,
                #requestTimeout: requestTimeout,
              }),
            ),
            returnValueForMissingStub: _FakePostgrestQueryBuilder_10<dynamic>(
              this,
              Invocation.method(#retry, [], {
                #enabled: enabled,
                #count: count,
                #requestTimeout: requestTimeout,
              }),
            ),
          )
          as _i4.PostgrestQueryBuilder<dynamic>);

  @override
  _i4.PostgrestQueryBuilder<dynamic> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestQueryBuilder_10<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
            returnValueForMissingStub: _FakePostgrestQueryBuilder_10<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i4.PostgrestQueryBuilder<dynamic>);

  @override
  _i4.PostgrestBuilder<U, U, dynamic> withConverter<U>(
    _i4.PostgrestConverter<U, dynamic>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_11<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
            returnValueForMissingStub: _FakePostgrestBuilder_11<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i4.PostgrestBuilder<U, U, dynamic>);

  @override
  _i4.PostgrestBuilder<dynamic, dynamic, dynamic> abortSignal(
    _i6.Future<void>? abortSignal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#abortSignal, [abortSignal]),
            returnValue: _FakePostgrestBuilder_11<dynamic, dynamic, dynamic>(
              this,
              Invocation.method(#abortSignal, [abortSignal]),
            ),
            returnValueForMissingStub:
                _FakePostgrestBuilder_11<dynamic, dynamic, dynamic>(
                  this,
                  Invocation.method(#abortSignal, [abortSignal]),
                ),
          )
          as _i4.PostgrestBuilder<dynamic, dynamic, dynamic>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_12(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
            returnValueForMissingStub: _FakeUri_12(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value, url]),
            returnValue: _FakeUri_12(
              this,
              Invocation.method(#overrideSearchParams, [key, value, url]),
            ),
            returnValueForMissingStub: _FakeUri_12(
              this,
              Invocation.method(#overrideSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  _i6.Stream<dynamic> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i6.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i6.Stream<dynamic>.empty(),
          )
          as _i6.Stream<dynamic>);

  @override
  _i6.Future<dynamic> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<U> then<U>(
    _i6.FutureOr<U> Function(dynamic)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i6.Future<U>.value(v),
                ) ??
                _FakeFuture_13<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
            returnValueForMissingStub:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i6.Future<U>.value(v),
                ) ??
                _FakeFuture_13<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i6.Future<U>);

  @override
  _i6.Future<dynamic> timeout(
    Duration? timeLimit, {
    _i6.FutureOr<dynamic> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> whenComplete(_i6.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}

/// A class which mocks [RealtimeChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeChannel extends _i1.Mock implements _i3.RealtimeChannel {
  @override
  bool get joinedOnce =>
      (super.noSuchMethod(
            Invocation.getter(#joinedOnce),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Push get joinPush =>
      (super.noSuchMethod(
            Invocation.getter(#joinPush),
            returnValue: _FakePush_14(this, Invocation.getter(#joinPush)),
            returnValueForMissingStub: _FakePush_14(
              this,
              Invocation.getter(#joinPush),
            ),
          )
          as _i7.Push);

  @override
  _i3.RealtimePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeRealtimePresence_15(
              this,
              Invocation.getter(#presence),
            ),
            returnValueForMissingStub: _FakeRealtimePresence_15(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i3.RealtimePresence);

  @override
  String get broadcastEndpointURL =>
      (super.noSuchMethod(
            Invocation.getter(#broadcastEndpointURL),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#broadcastEndpointURL),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#broadcastEndpointURL),
            ),
          )
          as String);

  @override
  String get subTopic =>
      (super.noSuchMethod(
            Invocation.getter(#subTopic),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#subTopic),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#subTopic),
            ),
          )
          as String);

  @override
  String get topic =>
      (super.noSuchMethod(
            Invocation.getter(#topic),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get params =>
      (super.noSuchMethod(
            Invocation.getter(#params),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.RealtimeClient get socket =>
      (super.noSuchMethod(
            Invocation.getter(#socket),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#socket),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#socket),
            ),
          )
          as _i3.RealtimeClient);

  @override
  bool get canPush =>
      (super.noSuchMethod(
            Invocation.getter(#canPush),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get joinRef =>
      (super.noSuchMethod(
            Invocation.getter(#joinRef),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#joinRef),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#joinRef),
            ),
          )
          as String);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isErrored =>
      (super.noSuchMethod(
            Invocation.getter(#isErrored),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isJoined =>
      (super.noSuchMethod(
            Invocation.getter(#isJoined),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isJoining =>
      (super.noSuchMethod(
            Invocation.getter(#isJoining),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLeaving =>
      (super.noSuchMethod(
            Invocation.getter(#isLeaving),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set joinedOnce(bool? value) => super.noSuchMethod(
    Invocation.setter(#joinedOnce, value),
    returnValueForMissingStub: null,
  );

  @override
  set joinPush(_i7.Push? value) => super.noSuchMethod(
    Invocation.setter(#joinPush, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i3.RealtimePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set broadcastEndpointURL(String? value) => super.noSuchMethod(
    Invocation.setter(#broadcastEndpointURL, value),
    returnValueForMissingStub: null,
  );

  @override
  set params(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#params, value),
    returnValueForMissingStub: null,
  );

  @override
  void rejoinUntilConnected() => super.noSuchMethod(
    Invocation.method(#rejoinUntilConnected, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.RealtimeChannel subscribe([
    void Function(_i3.RealtimeSubscribeStatus, Object?)? callback,
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [callback, timeout]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#subscribe, [callback, timeout]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#subscribe, [callback, timeout]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  List<_i3.SinglePresenceState> presenceState() =>
      (super.noSuchMethod(
            Invocation.method(#presenceState, []),
            returnValue: <_i3.SinglePresenceState>[],
            returnValueForMissingStub: <_i3.SinglePresenceState>[],
          )
          as List<_i3.SinglePresenceState>);

  @override
  _i6.Future<_i3.ChannelResponse> track(
    Map<String, dynamic>? payload, [
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#track, [payload, opts]),
            returnValue: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
            returnValueForMissingStub: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i3.ChannelResponse>);

  @override
  _i6.Future<_i3.ChannelResponse> untrack([
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#untrack, [opts]),
            returnValue: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
            returnValueForMissingStub: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i3.ChannelResponse>);

  @override
  _i3.RealtimeChannel onPostgresChanges({
    required _i3.PostgresChangeEvent? event,
    String? schema,
    String? table,
    _i3.PostgresChangeFilter? filter,
    List<_i3.PostgresChangeFilter>? filters,
    List<String>? select,
    required void Function(_i3.PostgresChangePayload)? callback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onPostgresChanges, [], {
              #event: event,
              #schema: schema,
              #table: table,
              #filter: filter,
              #filters: filters,
              #select: select,
              #callback: callback,
            }),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPostgresChanges, [], {
                #event: event,
                #schema: schema,
                #table: table,
                #filter: filter,
                #filters: filters,
                #select: select,
                #callback: callback,
              }),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPostgresChanges, [], {
                #event: event,
                #schema: schema,
                #table: table,
                #filter: filter,
                #filters: filters,
                #select: select,
                #callback: callback,
              }),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onBroadcast({
    required String? event,
    required void Function(Map<String, dynamic>)? callback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onBroadcast, [], {
              #event: event,
              #callback: callback,
            }),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onBroadcast, [], {
                #event: event,
                #callback: callback,
              }),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onBroadcast, [], {
                #event: event,
                #callback: callback,
              }),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onPresenceSync(
    void Function(_i3.RealtimePresenceSyncPayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceSync, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceSync, [callback]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceSync, [callback]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onPresenceJoin(
    void Function(_i3.RealtimePresenceJoinPayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceJoin, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceJoin, [callback]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceJoin, [callback]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onPresenceLeave(
    void Function(_i3.RealtimePresenceLeavePayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceLeave, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceLeave, [callback]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceLeave, [callback]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onSystemEvents(void Function(dynamic)? callback) =>
      (super.noSuchMethod(
            Invocation.method(#onSystemEvents, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onSystemEvents, [callback]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onSystemEvents, [callback]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel onEvents(
    String? type,
    _i10.ChannelFilter? filter,
    _i3.BindingCallback? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onEvents, [type, filter, callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onEvents, [type, filter, callback]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onEvents, [type, filter, callback]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i3.RealtimeChannel off(String? type, Map<String, dynamic>? filter) =>
      (super.noSuchMethod(
            Invocation.method(#off, [type, filter]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#off, [type, filter]),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#off, [type, filter]),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  _i7.Push push(
    _i11.ChannelEvents? event,
    Map<String, dynamic>? payload, [
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#push, [event, payload, timeout]),
            returnValue: _FakePush_14(
              this,
              Invocation.method(#push, [event, payload, timeout]),
            ),
            returnValueForMissingStub: _FakePush_14(
              this,
              Invocation.method(#push, [event, payload, timeout]),
            ),
          )
          as _i7.Push);

  @override
  _i6.Future<void> httpSend({
    required String? event,
    required Object? payload,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#httpSend, [], {
              #event: event,
              #payload: payload,
              #timeout: timeout,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.ChannelResponse> sendBroadcastMessage({
    required String? event,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcastMessage, [], {
              #event: event,
              #payload: payload,
            }),
            returnValue: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
            returnValueForMissingStub: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i3.ChannelResponse>);

  @override
  _i6.Future<_i3.ChannelResponse> send({
    required _i10.RealtimeListenTypes? type,
    String? event,
    required Map<String, dynamic>? payload,
    Map<String, dynamic>? opts = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#send, [], {
              #type: type,
              #event: event,
              #payload: payload,
              #opts: opts,
            }),
            returnValue: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
            returnValueForMissingStub: _i6.Future<_i3.ChannelResponse>.value(
              _i3.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i3.ChannelResponse>);

  @override
  void updateJoinPayload(Map<String, dynamic>? payload) => super.noSuchMethod(
    Invocation.method(#updateJoinPayload, [payload]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<String> unsubscribe([Duration? timeout]) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [timeout]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#unsubscribe, [timeout]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#unsubscribe, [timeout]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  dynamic onMessage(String? event, dynamic payload, [String? ref]) =>
      super.noSuchMethod(
        Invocation.method(#onMessage, [event, payload, ref]),
        returnValueForMissingStub: null,
      );

  @override
  bool isMember(String? otherTopic) =>
      (super.noSuchMethod(
            Invocation.method(#isMember, [otherTopic]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void rejoin([Duration? timeout]) => super.noSuchMethod(
    Invocation.method(#rejoin, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  void forceRejoin([Duration? timeout]) => super.noSuchMethod(
    Invocation.method(#forceRejoin, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  void trigger(String? type, [dynamic payload, String? ref]) =>
      super.noSuchMethod(
        Invocation.method(#trigger, [type, payload, ref]),
        returnValueForMissingStub: null,
      );

  @override
  String replyEventName(String? ref) =>
      (super.noSuchMethod(
            Invocation.method(#replyEventName, [ref]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#replyEventName, [ref]),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#replyEventName, [ref]),
            ),
          )
          as String);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i8.Client {
  @override
  _i6.Future<_i8.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<_i8.Response>);

  @override
  _i6.Future<_i8.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<_i8.Response>);

  @override
  _i6.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i8.Response>);

  @override
  _i6.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i8.Response>);

  @override
  _i6.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i8.Response>);

  @override
  _i6.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i12.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.Response>.value(
              _FakeResponse_16(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i8.Response>);

  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i13.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i6.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
            returnValueForMissingStub: _i6.Future<_i13.Uint8List>.value(
              _i13.Uint8List(0),
            ),
          )
          as _i6.Future<_i13.Uint8List>);

  @override
  _i6.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i6.Future<_i8.StreamedResponse>.value(
              _FakeStreamedResponse_17(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i8.StreamedResponse>.value(
              _FakeStreamedResponse_17(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i6.Future<_i8.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i5.GoTrueClient {
  @override
  _i5.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_18(
              this,
              Invocation.getter(#admin),
            ),
            returnValueForMissingStub: _FakeGoTrueAdminApi_18(
              this,
              Invocation.getter(#admin),
            ),
          )
          as _i5.GoTrueAdminApi);

  @override
  _i5.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_19(this, Invocation.getter(#mfa)),
            returnValueForMissingStub: _FakeGoTrueMFAApi_19(
              this,
              Invocation.getter(#mfa),
            ),
          )
          as _i5.GoTrueMFAApi);

  @override
  _i5.GoTrueOAuthApi get oauth =>
      (super.noSuchMethod(
            Invocation.getter(#oauth),
            returnValue: _FakeGoTrueOAuthApi_20(
              this,
              Invocation.getter(#oauth),
            ),
            returnValueForMissingStub: _FakeGoTrueOAuthApi_20(
              this,
              Invocation.getter(#oauth),
            ),
          )
          as _i5.GoTrueOAuthApi);

  @override
  _i5.GoTruePasskeyApi get passkey =>
      (super.noSuchMethod(
            Invocation.getter(#passkey),
            returnValue: _FakeGoTruePasskeyApi_21(
              this,
              Invocation.getter(#passkey),
            ),
            returnValueForMissingStub: _FakeGoTruePasskeyApi_21(
              this,
              Invocation.getter(#passkey),
            ),
          )
          as _i5.GoTruePasskeyApi);

  @override
  _i6.Stream<_i5.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i6.Stream<_i5.AuthState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i5.AuthState>.empty(),
          )
          as _i6.Stream<_i5.AuthState>);

  @override
  _i6.Stream<_i5.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i6.Stream<_i5.AuthState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i5.AuthState>.empty(),
          )
          as _i6.Stream<_i5.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i5.GoTrueAdminApi? value) => super.noSuchMethod(
    Invocation.setter(#admin, value),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i5.GoTrueMFAApi? value) => super.noSuchMethod(
    Invocation.setter(#mfa, value),
    returnValueForMissingStub: null,
  );

  @override
  set oauth(_i5.GoTrueOAuthApi? value) => super.noSuchMethod(
    Invocation.setter(#oauth, value),
    returnValueForMissingStub: null,
  );

  @override
  set passkey(_i5.GoTruePasskeyApi? value) => super.noSuchMethod(
    Invocation.setter(#passkey, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i5.Session?> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i6.Future<_i5.Session?>.value(),
            returnValueForMissingStub: _i6.Future<_i5.Session?>.value(),
          )
          as _i6.Future<_i5.Session?>);

  @override
  _i6.Future<_i5.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<_i5.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i5.OtpChannel? channel = _i5.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<_i5.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<_i5.OAuthResponse> getOAuthSignInUrl({
    required _i5.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i6.Future<_i5.OAuthResponse>.value(
              _FakeOAuthResponse_23(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.OAuthResponse>.value(
              _FakeOAuthResponse_23(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.OAuthResponse>);

  @override
  _i6.Future<_i5.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i6.Future<_i5.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_24(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i5.AuthSessionUrlResponse>.value(
                  _FakeAuthSessionUrlResponse_24(
                    this,
                    Invocation.method(#exchangeCodeForSession, [authCode]),
                  ),
                ),
          )
          as _i6.Future<_i5.AuthSessionUrlResponse>);

  @override
  _i6.Future<_i5.AuthResponse> signInWithIdToken({
    required _i5.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<_i5.AuthResponse> signInWithWeb3({
    required _i5.Web3Chain? chain,
    required String? message,
    required String? signature,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithWeb3, [], {
              #chain: chain,
              #message: message,
              #signature: signature,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInWithWeb3, [], {
                  #chain: chain,
                  #message: message,
                  #signature: signature,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#signInWithWeb3, [], {
                  #chain: chain,
                  #message: message,
                  #signature: signature,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i5.OtpChannel? channel = _i5.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i5.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i5.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i5.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i5.ResendResponse> resend({
    String? email,
    String? phone,
    required _i5.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i5.ResendResponse>.value(
              _FakeResendResponse_25(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.ResendResponse>.value(
              _FakeResendResponse_25(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.ResendResponse>);

  @override
  _i6.Future<_i5.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i6.Future<_i5.UserResponse>.value(
              _FakeUserResponse_26(this, Invocation.method(#getUser, [jwt])),
            ),
            returnValueForMissingStub: _i6.Future<_i5.UserResponse>.value(
              _FakeUserResponse_26(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i6.Future<_i5.UserResponse>);

  @override
  _i6.Future<_i5.UserResponse> updateUser(
    _i5.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i6.Future<_i5.UserResponse>.value(
              _FakeUserResponse_26(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.UserResponse>.value(
              _FakeUserResponse_26(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i6.Future<_i5.UserResponse>);

  @override
  _i6.Future<_i5.AuthResponse> setSession(
    String? refreshToken, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSession,
              [refreshToken],
              {#accessToken: accessToken},
            ),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(
                  #setSession,
                  [refreshToken],
                  {#accessToken: accessToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(
                  #setSession,
                  [refreshToken],
                  {#accessToken: accessToken},
                ),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<_i5.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i6.Future<_i5.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_24(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i5.AuthSessionUrlResponse>.value(
                  _FakeAuthSessionUrlResponse_24(
                    this,
                    Invocation.method(
                      #getSessionFromUrl,
                      [originUrl],
                      {#storeSession: storeSession},
                    ),
                  ),
                ),
          )
          as _i6.Future<_i5.AuthSessionUrlResponse>);

  @override
  _i6.Future<void> signOut({
    _i5.SignOutScope? scope = _i5.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i6.Future<List<_i5.UserIdentity>>.value(
              <_i5.UserIdentity>[],
            ),
            returnValueForMissingStub: _i6.Future<List<_i5.UserIdentity>>.value(
              <_i5.UserIdentity>[],
            ),
          )
          as _i6.Future<List<_i5.UserIdentity>>);

  @override
  _i6.Future<_i5.AuthResponse> linkIdentityWithIdToken({
    required _i5.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  _i6.Future<_i5.OAuthResponse> getLinkIdentityUrl(
    _i5.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i6.Future<_i5.OAuthResponse>.value(
              _FakeOAuthResponse_23(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.OAuthResponse>.value(
              _FakeOAuthResponse_23(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i5.OAuthResponse>);

  @override
  _i6.Future<void> unlinkIdentity(_i5.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i5.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_22(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i6.Future<_i5.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i5.AuthChangeEvent? event, {
    _i5.Session? session,
    bool? broadcast = true,
    _i5.SignOutReason? signOutReason,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast, #signOutReason: signOutReason},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_27(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
            returnValueForMissingStub: _FakeObject_27(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);

  @override
  _i6.Future<_i5.GetClaimsResponse> getClaims([
    String? jwt,
    _i5.GetClaimsOptions? options,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getClaims, [jwt, options]),
            returnValue: _i6.Future<_i5.GetClaimsResponse>.value(
              _FakeGetClaimsResponse_28(
                this,
                Invocation.method(#getClaims, [jwt, options]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.GetClaimsResponse>.value(
              _FakeGetClaimsResponse_28(
                this,
                Invocation.method(#getClaims, [jwt, options]),
              ),
            ),
          )
          as _i6.Future<_i5.GetClaimsResponse>);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i5.Session {
  @override
  String get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
          )
          as String);

  @override
  String get tokenType =>
      (super.noSuchMethod(
            Invocation.getter(#tokenType),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
          )
          as String);

  @override
  _i5.User get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUser_29(this, Invocation.getter(#user)),
            returnValueForMissingStub: _FakeUser_29(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i5.User);

  @override
  bool get isExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isExpired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isExpiredWithoutMargin =>
      (super.noSuchMethod(
            Invocation.getter(#isExpiredWithoutMargin),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set expiresAt(int? value) => super.noSuchMethod(
    Invocation.setter(#expiresAt, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Session copyWith({
    String? accessToken,
    int? expiresIn,
    String? refreshToken,
    String? tokenType,
    String? providerToken,
    String? providerRefreshToken,
    _i5.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #accessToken: accessToken,
              #expiresIn: expiresIn,
              #refreshToken: refreshToken,
              #tokenType: tokenType,
              #providerToken: providerToken,
              #providerRefreshToken: providerRefreshToken,
              #user: user,
            }),
            returnValue: _FakeSession_30(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
            returnValueForMissingStub: _FakeSession_30(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
          )
          as _i5.Session);
}
